[admiral]
items = ["left", "menu", "workspaces",
         "center", "clock",
         "right", "mail", "volume", "ram", "net", "battery", "pow"]

[workspaces]
path = "./workspace"

[title]
path = "xtitle -s -t 100"

[mail]
path = "./mail"
reload = 30

[volume]
path = "./vol"
reload = 0.1

[ram]
path = "./ram"
reload = 0.5

[net]
path = "./net"
reload = 20

[battery]
path = "./battery"
reload = 10

[clock]
path = "./clock"
reload = 1

# Clickable areas
[pow]
path = 'echo "%{A:. $HOME/.config/admiral.d/popups/power/power:}%{B#dc322f}%{F#fdf6e3}    %{F-}%{B-}%{A}"'
static = true

[menu]
path = 'echo "%{A:. $HOME/.config/admiral.d/popups/todo/todo:}%{B#cb4b16}%{F#fdf6e3}    %{F-}%{B-}%{A}"'
static = true

# Used for formatting lemonbar
[left]
path = "echo '%{l}'"
static = true

[center]
path = "echo '%{c}'"
static = true

[right]
path = "echo '%{r}'"
static = true
